service_name: travis-ci
coverage_clover: /home/travis/build/nixsolutions/laravel-api-boilerplate/build/logs/clover.xml
json_path: /home/travis/build/nixsolutions/laravel-api-boilerplate/build/logs/coveralls-upload.json
